fcrudapp/urls.py
from django.urls import path
from fcrudapp import views
from .views import *
app_name='fcrudapp'
urlpatterns=[
path('',views.index,name='home'),
path('add/',views.book_create,name='add'),
path('update/<int:pk>/',views.book_update,name='update'),
path('delete/<int:pk>/',views.book_delete,name='delete'),
path('book/<int:pk>/detail/',BookDetailView.as_view(),name='bookdetail'),
path('book/create/',BookCreateView.as_view(),name='bookcreate'),
]

fcrudproj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fcrudapp.urls'))
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fcrudapp/models.py
from django.db import models

class Book(models.Model):
	title=models.CharField(max_length=100)
	pages=models.IntegerField()

	def __str__(self):
		return self.title

def get_absolute_url(self):
	return reverse('bookdetail',kwargs={'pk':str(self.pk)})

fcrudapp/forms.py
from django import forms

from .models import Book

class BookForm(forms.ModelForm):
	class Meta:
		model=Book
		fields='__all__'

class BookCreateForm(forms.ModelForm):
	class Meta:
		model=Book
		fields='__all__'

fcrudapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from .forms import BookForm
from .forms import BookCreateForm
from django.views.generic import *
from django.views.generic.base import View
from django.urls import reverse_lazy



def index(request):
    template = 'list.html'
    book = Book.objects.all()
    context = {'book': book}
    return render(request, template, context)


def book_create(request):
    template = 'form.html'
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('fcrudapp:home')

    context = {"form1": form}
    return render(request, template, context)


def book_update(request, pk):
    template = 'form.html'
    book = get_object_or_404(Book, pk=pk)
    print(book, '*narendra*')
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('fcrudapp:home')
    context = {"form": form}
    return render(request, template, context)


def book_delete(request, pk):
    template = 'delete.html'
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('fcrudapp:home')
    context = {'book': book}
    return render(request, template, context)


class BookDetailView(DetailView):
    template_name='bookdetail.html'
    model=Book
    context_object_name='bookdetail'

class BookCreateView(CreateView):
    def get(self,request,*args,**kwargs):
        context={'form':BookCreateForm()}
        return render(request,'bookcreate.html',context)
    def post(self,request,*args,**kwargs):
        form=BookCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        return render(request,'bookcreate.html',{'form':form})

templates/about-us.html
{% for book in books %}
{{book.title}}
{{book.pages}}
<br>
{% endfor %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
	{% block content %}
	{% endblock %}

</body>
</html>

templates/bookcreate.html
<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
	
</form>

templates/bookdetail.html
<h1>Welcome to Book Detail</h1>
{{bookdetail.title}}
<h2>{{bookdetail.pages}}
{{bookdetail.id}}

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form class="" method="post">
	{% csrf_token %}
	Are You Sure Want To delete it ?
	<input type="submit" name="" value="submit">

	


</form>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block content %}
<form class="" method="POST">
	{% csrf_token %}
	{{form1.as_p}}
	<input type="submit" name="" value="submit">
</form>

{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'fcrudapp:home' %}">Back to home</a>
<table class="table table-bordered">
	<thead>
		<th>Title</th>
		<th>Pages</th>
		<th>Activity</th>
	</thead>
	<tbody>
		<a href="{% url 'fcrudapp:add' %}">add</a>
		{% for b in book %}
		<tr>
			<td>{{b.title}}</td>
			<td>{{b.pages}}</td>
			<td>
				<a href="{% url 'fcrudapp:update' b.id %}">Update</a>
				<a href="{% url 'fcrudapp:delete' b.id %}">Delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>

</table>
{% endblock %}